# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 12:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_no', models.IntegerField(default=0)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('userphoto', models.ImageField(null=True, upload_to='static/music/userimages', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'bmp', 'jpg'], 'file exteion not valid')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.FileField(upload_to='static/callmemaybe/userimages', validators=[django.core.validators.FileExtensionValidator(['wav'], 'file format not supported')])),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.Customer')),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('recording_length', models.IntegerField(default=0)),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.Recordings')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('userphoto', models.ImageField(null=True, upload_to='static/music/userimages', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'bmp', 'jpg'], 'file exteion not valid')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recordings',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.Staff'),
        ),
    ]
