# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 21:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20180210_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='recording',
            field=models.FileField(upload_to='static/callmemaybe/userimages', validators=[django.core.validators.FileExtensionValidator(['wav'], ['mp3'], 'file format not supported')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='userphoto',
            field=models.ImageField(null=True, upload_to='static/userimages', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'bmp', 'jpg'], 'file exteion not valid')]),
        ),
    ]
