# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 21:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20180211_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordings',
            name='recording',
            field=models.FileField(upload_to='static/callmemaybe/userimages', validators=[django.core.validators.FileExtensionValidator(['wav', 'mp3'], 'file format not supported')]),
        ),
    ]
