# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20180211_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='trending',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
